version: "3.9"
services:
  backend:
    build: .
    depends_on: [ database ]
    ports:
      - "80:80"
    volumes:
      - .:/app

  database:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: 'hospital_db'
      MYSQL_USER: 'amir'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./AssignmentSQL.sql:/docker-entrypoint-initdb.d/1.sql

volumes:
  mysql-data: